version: '3.8'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: movies
      MONGODB_DATABASE: movies
      DATABASE_URL: mongodb://mongo:27017/
    restart: always
    networks:
      - app_net
    ports:
      - 27017:27017
  my_node_app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_net
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    networks:
      - app_net
    ports:
      - "8081:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/swagger/openapi.json
networks:
  app_net:
    external: true
